import { createActions } from 'reduxsauce'

const { Types, Creators} = createActions({ 
    postHospitalBasicDetailsRequest : ['data'],
    postHospitalBasicDetailsSuccess: ['data'],
    postHospitalBasicDetailsError: ['error'],
    getHospitalBasicDetailsRequest : ['data'],
    getHospitalBasicDetailsSuccess : ['data'],
    getHospitalBasicDetailsError : ['error'],
    updateHospitalBasicDetailsRequest : ['data'],
    updateHospitalBasicDetailsSuccess : ['data'],
    updateHospitalBasicDetailsError : ['error'],
    getAllHospitalsBasicDetailsRequest: ['data'],
    getAllHospitalsBasicDetailsSuccess: ['data'],
    getAllHospitalsBasicDetailsError: ['error'],
    deleteHospitalRequest: ['data'],
    deleteHospitalSuccess: ['data'],
    deleteHospitalError: ['error'],

    getHospitalDepartmentsRequest : ['data'],
    getHospitalDepartmentsSuccess : ['data'],
    getHospitalDepartmentsError : ['error'],
    postHospitalDepartmentsRequest: ['data'],
    postHospitalDepartmentsSuccess: ['data'],
    postHospitalDepartmentsError: ['error'],
    
    getHospitalProceduresRequest: ['data'],
    getHospitalProceduresSuccess: ['data'],
    getHospitalProceduresError: ['error'],
    postHospitalProceduresRequest: ['data'],
    postHospitalProceduresSuccess: ['data'],
    postHospitalProceduresError: ['error'],
    updateHospitalProceduresRequest: ['data'],
    updateHospitalProceduresSuccess: ['data'],
    updateHospitalProceduresError: ['error'],
    getProceduresFromDepartmentRequest: ['data'],
    getProceduresFromDepartmentSuccess: ['data'],
    getProceduresFromDepartmentError: ['error'],
    getProcedureDetailFromProcedureIdRequest: ['data'],
    getProcedureDetailFromProcedureIdSuccess: ['data'],
    getProcedureDetailFromProcedureIdError: ['error'],
    deleteProcedureRequest: ['data'],
    deleteProcedureSuccess: ['data'],
    deleteProcedureError: ['error'],

    getHospitalWardsBedsRequest: ['data'],
    getHospitalWardsBedsSuccess: ['data'],
    getHospitalWardsBedsError: ['error'],
    postHospitalWardsBedsRequest: ['data'],
    postHospitalWardsBedsSuccess: ['data'],
    postHospitalWardsBedsError: ['error'],

    getAllDoctorsRequest: ['data'],
    getAllDoctorsSuccess: ['data'],
    getAllDoctorsError: ['error'],
    postDoctorInfoRequest: ['data'],
    postDoctorInfoSuccess: ['data'],
    postDoctorInfoError: ['error'],
    getDoctorInfoRequest: ['data'],
    getDoctorInfoSuccess: ['data'],
    getDoctorInfoError: ['error'],
    updateDoctorInfoRequest: ['data'],
    updateDoctorInfoSuccess: ['data'],
    updateDoctorInfoError: ['error'],
    deleteDoctorRequest: ['data'],
    deleteDoctorSuccess: ['data'],
    deleteDoctorError: ['error'],
    getAllDoctorsFromDeptRequest: ['data'],
    getAllDoctorsFromDeptSuccess: ['data'],
    getAllDoctorsFromDeptError: ['error'],

    getAmenitiesRequest: ['data'],
    getAmenitiesSuccess: ['data'],
    getAmenitiesError: ['error'],
    postAmenitiesRequest: ['data'],
    postAmenitiesSuccess: ['data'],
    postAmenitiesError: ['error'],

    getInsurancesRequest: ['data'],
    getInsurancesSuccess: ['data'],
    getInsurancesError: ['error'],
    postInsurancesRequest: ['data'],
    postInsurancesSuccess: ['data'],
    postInsurancesError: ['error'],

    getAllAdminsRequest: ['data'],
    getAllAdminsSuccess: ['data'],
    getAllAdminsError: ['error'],
    postAdminDetailsRequest: ['data'],
    postAdminDetailsSuccess: ['data'],
    postAdminDetailsError: ['error'],
    getAdminDetailsFromIdRequest: ['data'],
    getAdminDetailsFromIdSuccess: ['data'],
    getAdminDetailsFromIdError: ['error'],
    updateAdminDetailsRequest: ['data'],
    updateAdminDetailsSuccess: ['data'],
    updateAdminDetailsError: ['error'],
    deleteAdminRequest: ['data'],
    deleteAdminSuccess: ['data'],
    deleteAdminError: ['error'],

    getHospitalReviewRequest: ['data'],
    getHospitalReviewSuccess: ['data'],
    getHospitalReviewError: ['error'],
    postHospitalReviewRequest: ['data'],
    postHospitalReviewSuccess: ['data'],
    postHospitalReviewError: ['error'],
})

export const Constants = Types
export default Creators